### ISSUE TITLE
Invalid Syntax Error ?

### ISSUE THREAD

**Issue by jhw** [metrasynth/radiant-voices#17]
Hi,

I have RV installed fine using virtualenv, having recently upgraded from Python2.7 to Python3.5; however when I try and run a `hello.py` example I get the following syntax error. Is easily resolved by commenting out the line in the source code, but why am I getting this (I am not 100% up to speed with Python3.5 features/syntax)

Many thanks

```
(hello_sunvox) justin@justin-XPS-13-9360:~/work/hello_sunvox$ python3 drumsynth/hello.py 32 14
Traceback (most recent call last):
  File "drumsynth/hello.py", line 69, in <module>
    project=read_project("blank.sunvox")
  File "/home/justin/work/hello_sunvox/drumsynth/sunvox.py", line 3, in read_project
    return read_sunvox_file(open(filename, 'rb'))
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/readers/reader.py", line 11, in read_sunvox_file
    from rv.readers.initial import InitialReader
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/readers/initial.py", line 2, in <module>
    from rv.readers.sunsynth import SunSynthReader
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/readers/sunsynth.py", line 3, in <module>
    from rv.readers.module import ModuleReader
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/readers/module.py", line 7, in <module>
    from rv.modules import MODULE_CLASSES, Chunk, Module
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/modules/__init__.py", line 47, in <module>
    from .metamodule import MetaModule
  File "/home/justin/work/hello_sunvox/lib/python3.5/site-packages/rv/modules/metamodule.py", line 28
    s = f'_{s}'
              ^
```

**Comment by gldnspud** [comment]
Python 3.6 or higher is required for Radiant Voices. No plans to support Python 3.5 or earlier.

Although Python 3.7 just came out, we will go ahead and keep Python 3.6 compatibility for some time yet, but will probably recommend Python 3.7 for its overall performance improvements.
