### ISSUE TITLE
Problem serialising track with samples

### ISSUE THREAD

**Issue by jhw** [metrasynth/radiant-voices#29]
I have a simple script which "round trips" a file, just to check input/output serialisation is working -

```
from rv.lib.iff import write_chunk       

def dump_project(project, filename):
    with open(filename, 'wb') as f:
        for name, value in project.chunks():
            if not name:
                continue
            write_chunk(f, name, value)
            
if __name__=="__main__":
    try:
        import sys, os
        if len(sys.argv) < 2:
            raise RuntimeError("Please enter filename")
        filename=sys.argv[1]
        if not os.path.exists(filename):
            raise RuntimeError("File does not exist")
        if not filename.endswith(".sunvox"):
            raise RuntimeError("File must be a .sunvox file")
        from rv.readers.reader import read_sunvox_file
        proj=read_sunvox_file(filename)
        destfilename="tmp/%s" % filename.split("/")[-1]
        dump_project(proj, destfilename)
    except RuntimeError as error:
        print ("Error: %s" % str(error))
```

Works the vast majority of the time , but fails occasionally -

```
justin@justin-XPS-13-9360:~/work/$ python dev/roundtrip.py ~/packages/sunvox/examples/NightRadio\ -\ Mechanical\ Heart.sunvox 
Traceback (most recent call last):
  File "dev/roundtrip.py", line 23, in <module>
    dump_project(proj, destfilename)
  File "dev/roundtrip.py", line 5, in dump_project
    for name, value in project.chunks():
  File "/home/justin/work/seavox/lib/python3.6/site-packages/rv/project.py", line 155, in chunks
    for chunk in module.specialized_iff_chunks():
  File "/home/justin/work/seavox/lib/python3.6/site-packages/rv/modules/sampler.py", line 325, in specialized_iff_chunks
    for chunk in iter:
  File "/home/justin/work/seavox/lib/python3.6/site-packages/rv/modules/sampler.py", line 165, in chunks
    data += pack("<HH", x, y)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

Am pretty sure this is something to do with the samples in there; if I clone modules without sample data and try and serialise that, it works fine.

Also to be clear it's not *every* sample; just something to do with the samples in this particular track

**Comment by jhw** [comment]
Also seems to affect `module.detach()` for the affected modules, where I get -

```
ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

**Comment by gldnspud** [comment]
- [ ] find or create project that triggers this bug
- [ ] check logic of Python version
- [ ] check if it also occurs in JS version

**Comment by gldnspud** [comment]
@jhw do you happen to have an example project you could ZIP up and attach which triggers this bug?

**Comment by jhw** [comment]
probably somewhere but would need to look it out and recreate - gimme a few
days

**Comment by gldnspud** [comment]
> probably somewhere but would need to look it out and recreate - gimme a few days

OK thanks. No rush. Just want to see how it works with the new 1.0 release since there are several changes in the last 2 years.

**Comment by jhw** [comment]
TBH I can no longer remember what the issue was.

I did do a Gist recently in which i successfully managed to serialise a
sunvox file with some samples in it -

https://gist.github.com/jhw/44d4ab80a6c9b582f22a25afd91e3cdf

in particular this file -

https://gist.githubusercontent.com/jhw/44d4ab80a6c9b582f22a25afd91e3cdf/raw/db0e226748b2a9097184288979e249c6abde5d83/generate.py

in which I think you provided me with the all important code, in
`load_sample`

So seems fine, but maybe you can test with the above code or similar

Suggest you mark as Closed ?

Best wishes
